language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 1.1.5
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_script:
  - cd Platform/Platform.Tests
  - rm *.xproj
  - dotnet restore
script:
  - dotnet test 
