language: csharp  
sudo: required  
dist: trusty  
mono: latest
dotnet: 1.1.5
before_script:
  - cd Platform
  - dotnet restore Platform.dotnet.sln
  - dotnet build Platform.dotnet.sln
script:
  - cd Platform.Tests
  - rm Platform.Tests.Library.csproj
  - dotnet xunit -parallel none
after_success:
  - cd ../..
  - mkdir docfx
  - cd docfx
  - nuget install docfx.console
  - ls
  - git clone https://github.com/docascode/docfx-seed.git docfx-seed
  - mono docfx.console.2.28.2/tools/docfx.exe docfx-seed/docfx.json
