language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 1.1.5
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_script:
  - cd Platform
  - rm Platform.sln
  - dotnet migrate
  - dotnet restore
script:
  - cd Platform.Tests
  - dotnet test 
