language: csharp  
sudo: required  
dist: trusty  
mono: latest
dotnet: 1.1.5
env:
  global:
  - COMMIT_AUTHOR_EMAIL: "konard@me.com"
before_script:
  - dotnet restore Platform/Platform.dotnet.sln
  - dotnet build Platform/Platform.dotnet.sln
script:
  - dotnet test Platform/Platform.dotnet.sln
after_success:
  - cd ../..
  - nuget install docfx.console
  - ls
  - mono docfx.console.2.30.0/tools/docfx.exe docfx.json
  - ls doc/generated/site
  - ls doc/generated/site/doc
  - bash ./deploy.sh
