language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 1.1.5
before_script:
  - cd Platform
  - dotnet restore Platform.dotnet.sln
  - dotnet build Platform.dotnet.sln
script:
  - cd Platform.Tests
  - rm Platform.Tests.Library.csproj
  - dotnet xunit --help
