language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 1.1.5
before_script:
  - cd Platform
  - rm Platform.sln
  - rm -r Platform.Data.ConsoleTerminal
  - rm -r Platform.Data.IdClient
  - rm -r Platform.Data.IdServer
  - rm -r Platform.Data.Kernel.Tests
  - rm -r Platform.Data.Kernel
  - rm -r Platform.Data.MasterServer
  - rm -r Platform.Data.SlaveServer
  - rm -r Platform.Data.WebTerminal
  - rm -r Platform.Examples
  - rm -r Platform.Sandbox
  - rm -r Platform.WindowsAPI
  - dotnet migrate
  - ls Platform.Test
  - cat Platform.Communication/Platform.Communication.csproj
  - cat Platform.Helpers/Platform.Helpers.csproj
  - cat Platform.Memory/Platform.Memory.csproj
  - cat Platform.Data.Core/Platform.Data.Core.csproj
  - cat Platform.Tests/Platform.Tests.csproj
  - dotnet restore
  - ls Platform.Tests
  - dotnet build
script:
  - cd Platform.Tests.Runner
  - dotnet xunit
